name: 00 BACK Secret Sync Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        #type: environment
        #required: true
        type: choice
        options: 
        - dev
        - dev-old
        - qa
        - prod
      reponame:
        description: 'Repository name to run tests against'
        type: string
        required: true
      dry_run:
        description: 'dry run tests against'
        type: boolean
        required: true
        default: true

jobs:

  sync-dev:
    timeout-minutes: 30
    name: Syncing secrets DEV
    if: ${{ github.event.inputs.environment == 'dev'}}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: google/secrets-sync-action@v1.7.1
        name: tmpl-secrets-sync
        continue-on-error: true
        with:
          dry_run: ${{ github.event.inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
            \bBlue-Express/${{ github.event.inputs.reponame }}\b
          environment: development
          github_token: ${{ secrets.SYNC_TOKEN }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.EKS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}

  sync-dev-old:
    timeout-minutes: 30
    name: Syncing secrets DEV-OLD
    if: ${{ github.event.inputs.environment == 'dev-old'}}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: google/secrets-sync-action@v1.7.1
        name: tmpl-secrets-sync
        continue-on-error: true
        with:
          dry_run: ${{ github.event.inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
            \bBlue-Express/${{ github.event.inputs.reponame }}\b
          environment: develop
          github_token: ${{ secrets.SYNC_TOKEN }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.EKS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}

  sync-qa:
    timeout-minutes: 30
    name: Syncing secrets QA
    if: ${{ github.event.inputs.environment == 'qa'}}
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: google/secrets-sync-action@v1.7.1
        continue-on-error: true
        with:
          dry_run: ${{ github.event.inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
              \bBlue-Express\/${{ github.event.inputs.reponame }}\b
          environment: staging
          github_token: ${{ secrets.SYNC_TOKEN }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.EKS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}

  sync-prod:
    timeout-minutes: 30
    name: Syncing secrets PROD
    if: ${{ github.event.inputs.environment == 'prod'}}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: google/secrets-sync-action@v1.7.1
        name: srv-integrations-secrets-sync
        continue-on-error: true
        with:
          dry_run: ${{ github.event.inputs.dry_run }}
          secrets: |
            AWS_ASSUME_ROLE
            AWS_REGION
            AWS_KUBECONFIG
            KONG_HOST
            KEYCLOAK_HOST
          repositories: |
            \bBlue-Express\/${{ github.event.inputs.reponame }}\b
          environment: production
          github_token: ${{ secrets.SYNC_TOKEN }}
        env:
          AWS_ASSUME_ROLE: ${{secrets.AWS_ASSUME_ROLE_EKS}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_KUBECONFIG: ${{secrets.EKS_KUBECONFIG}}
          KONG_HOST:  ${{secrets.KONG_HOST}}
          KEYCLOAK_HOST:  ${{secrets.KEYCLOAK_HOST}}
